@Catalog.API_HostAddress = http://localhost:5222
@ApiVersion = 1.0

GET {{Catalog.API_HostAddress}}/api/catalog/items?api-version={{ApiVersion}}

###

GET {{Catalog.API_HostAddress}}/api/catalog/items/type/1/brand/2?api-version={{ApiVersion}}

###
GET {{Catalog.API_HostAddress}}/api/catalog/catalogbrands?api-version={{ApiVersion}}

###
GET {{Catalog.API_HostAddress}}/api/catalog/catalogtypes?api-version={{ApiVersion}}

###

POST http://localhost:5222/api/catalog/items?api-version={{ApiVersion}}
Content-Type: application/json

{
  "name": "Item1",
  "description": "Description1",
  "price": 100,
  "pictureFileName": "1.webp",
  "AvailableStock": 33,
  "RestockThreshold": 10,
  "MaxStockThreshold": 100,
  "CatalogTypeId": 1,
  "CatalogBrandId": 1
}
